name: reading_habit_formation_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.3.2+2
  table_calendar: ^2.2.3
  intl: ^0.16.1

#  firebase関連
  firebase_core: ^0.5.0+1
  cloud_firestore: ^0.14.1+3
  firebase_auth: ^0.18.1+2
  google_sign_in: ^4.5.5
  firebase_database: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
